"""book table added

Revision ID: 079b2c5a24b0
Revises: 5d728fa6d2d2
Create Date: 2022-08-27 17:46:35.732849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079b2c5a24b0'
down_revision = '5d728fa6d2d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###



