"""versions table

Revision ID: b0646eb2f7c9
Revises: 
Create Date: 2022-08-27 18:16:28.812578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0646eb2f7c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stamp', sa.DateTime(), nullable=True),
    sa.Column('revisionnum', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('versions')
    # ### end Alembic commands ###



